spring:
  application:
    name: canchitas


  datasource:
    url: jdbc:postgresql://localhost:5433/canchitas_management_pruebas
    username: postgres
    password: admin

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

