spring:
  application:
    name: canchitas

  datasource:
    url: jdbc:postgresql://localhost:5439/canchitas_management
    username: postgres
    password: admin




  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update